#
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "testing the rest api",
    "important": true 
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Connected to MongoDb successfuly",
    "important": true
}